name: Android Release

on:
  push:
    tags:
      - "v*"     # Triggers only when you push a tag like v1.0, v1.1.2, etc.
  workflow_dispatch: # Allows you to run it manually from the GitHub Actions tab

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repository
      - name: Check out
        uses: actions/checkout@v3

      # 2) Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # 3) Cache Gradle files (optional, speeds up builds)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # 4) Build the release APK
      - name: Build Release
        run: ./gradlew assembleRelease

      # 5) Upload APK as an artifact (optional if you also plan to attach it to a Release)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      # 6) Create a GitHub Release and attach the APK
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}         # The name of the tag that triggered this workflow
          release_name: "Android Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
